id: P6E0B5200
initial_creation_type: ocr
source_metadata:
  volumes:
    1bd9c575f8344aa0a20915a78bf51fd3:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
